from django.conf.urls.defaults import *

urlpatterns = patterns('toolkit.views',
    url(r'^download/start/$', 'startDownload', name='startDownload'),
    url(r'^download/status/$', 'status', name='status'),
    url(r'^pmis/(\d+)$', 'page_pmis', name='page_pmis'),
    url(r'^category/new/redirect/(\S+)$', 'newCategory', name='categoryNewRedirect'),
    url(r'^category/new/group/$', 'createCategoryFromGroup', name='categoryFromGroup'),
    url(r'^category/new/page/$', 'createCategoryFromPage', name='categoryFromPage'),
    url(r'^category/new/$', 'newCategory', name='categoryNew'),
    url(r'^category/start/$', 'startCategoryCreation', name='categoryCreate'),
    url(r'^category/(\d+)/start/$', 'startCreation', name='categoryCreate2'),
    url(r'^category/add/(\w+)$', 'addSeed', name='addSeed'),
    url(r'^category/delete/(\w+)$', 'deleteSeed', name='deleteSeed'),
    url(r'^category/(\d+)/read/$', 'markRead', name='categoryRead'),
    url(r'^category/rename/$', 'rename', name='categoryRename'),
    url(r'^category/status/(\d+)$', 'categoryStatus', name='categoryStatus'),
    url(r'^category/reset/(\d+)$', 'categoryReset', name='categoryReset'),
    url(r'^category/notifications/$', 'getNotifications', name='categoryNotifications'),
    url(r'^newuser/(\S+)/$', 'newUser', name='newUser_redirect'),
    url(r'^newuser/$', 'newUser', name='newUser'),
    url(r'^category/test/(\d+)$', 'testCategory', name='testCategory'),
    url(r'^login/test/(\d+)$', 'testLogin', name='testLogin'),
)
